In [13]:
from __future__ import print_function
import numpy as np

In [14]:
x = np.asarray([[1,2],[3,4]], dtype=np.float32)
print(x)

[[ 1.  2.]
 [ 3.  4.]]


In [15]:
c = np.asarray([[4,5],[6,7]], dtype=np.float32)
print(c)

[[ 4.  5.]
 [ 6.  7.]]


In [16]:
print(np.dot(c,x))

[[ 19.  28.]
 [ 27.  40.]]
